 CREATE TABLE User( id INT NOT NULL AUTO_INCREMENT PRIMARY KEY , 
	nom VARCHAR(40) NOT NULL , 
	prenom VARCHAR(40) NOT NULL , 
	password VARCHAR(40) NOT NULL );

CREATE TABLE GenreMusic (id_Genre INT  AUTO_INCREMENT PRIMARY KEY, 
	nom_Genre VARCHAR (40) NOT NULL);

 CREATE TABLE Amis(id1_User INT ,
	 id2_User INT ,
	FOREIGN KEY (id1_User)REFERENCES User (id),
	FOREIGN KEY (id2_User)REFERENCES User (id) );


CREATE TABLE Music(id_Music INT PRIMARY KEY ,
	id_User INT , 
	titre VARCHAR(40) ,
	 album VARCHAR(60) , 
	artiste VARCHAR(40),
	FOREIGN KEY(id_User) REFERENCES User(id));